/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './content/**/*.{md,mdx,json}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
      },
      maxWidth: {
        container: '1120px',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
        '4xl': '2rem',
      },
      boxShadow: {
        elev: '0 12px 32px rgba(0,0,0,.08)',
        'elev-lg': '0 30px 70px rgba(0,0,0,.10)',
        'elev-xl': '0 42px 90px rgba(0,0,0,.12)',
        e1: 'var(--shadow-xs)',
        e2: 'var(--shadow-sm)',
        e3: 'var(--shadow)',
        e4: 'var(--shadow-md)',
        e5: 'var(--shadow-lg)',
        e6: 'var(--shadow-xl)',
      },
      colors: {
        ink: 'var(--ink)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted)',
        border: 'var(--border)',
        surface: 'var(--surface)',
        canvas: 'var(--canvas)',
        eggshell: 'var(--eggshell)',
        'eggshell-2': 'var(--eggshell-2)',
        glass: 'var(--glass)',
        'glass-2': 'var(--glass-2)',
        'glass-3': 'var(--glass-3)',
        'glass-border': 'var(--glass-border)',
        'glass-border-hover': 'var(--glass-border-hover)',
        'primary-text': 'var(--primary-text)',
        'secondary-text': 'var(--secondary-text)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error: 'var(--error)',
        info: 'var(--info)',
        brand: {
          500: '#6f69f6',
          600: '#5c55f1',
        },
        primary: '#6f69f6',
        'primary-hover': '#5c55f1',
        secondary: '#a06ef6',
      },
    },
  },
  plugins: [],
};
