import type { SVGProps, ComponentType } from 'react';

declare module '@/components/icons' {
  // During development, the icons module may not exist until generated by SVGR.
  // This ambient module ensures type-checking passes. The actual module will
  // be generated at build time and expose named exports.
  const icons: Record<string, ComponentType<SVGProps<SVGSVGElement>>>;
  export = icons;
}
