name: Smoke Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ['**']

concurrency:
  group: ci-smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env.local
        run: |
          cat > .env.local <<'ENV'
          NEXT_PUBLIC_SITE_URL=http://localhost:3000
          NEXT_PUBLIC_BUSINESS_NAME=PrairieSignal
          NEXT_PUBLIC_BUSINESS_LOGO=/images/_prairie_signal_logo.png
          CONTACT_DISABLE_EMAIL=true
          ENV

      - name: Run smoke tests
        run: npm run smoke
